### ISSUE TITLE
rtai-config only supports a single kernel

### ISSUE THREAD

**Issue by zultron** [ShabbyX/RTAI#16]
`rtai-config` (as handed down from upstream) contains hard-coded parameters such as kernel version.  As such, even when multiple sets of RTAI kernel headers are installed, `rtai-config` can only be used to build against one of them.

This is a bigger problem when packaging, since `rtai-config` is part of the `librtai-dev` package, of which only one instance may be installed on a system.

This problem might only affect weird folk like me, who want to build and test against a variety of kernel versions, but I'd like to hear if others are affected, and would like to hear opinions on how this is best solved.

I see two solutions for packaging.  One is to install an `rtai-config` script with hard-coded parameters, as is done now, but in the same package with the RTAI modules and with a unique name (e.g. `rtai-config-$(uname -r)`).  The original `rtai-config` script could be replaced with a stub script that uses overrideable heuristics to pick a reasonable default set of kernel headers, and then executes the matching `rtai-config-<kver>` script.

Another is to modify the `rtai-config` script, removing those hard-coded parameters that may vary with kernel headers, and automatically generating them as above, by picking a reasonable default set of headers and extracting the correct values.

Discussion appreciated.

**Comment by mrudulachougule** [comment]
Hi,
I am working on rtai-4.1 version and i am able to compile rtai debian and installed on Ubuntu 14.04. Now I have below queries on rtai_lxrt module:
1) why rtai_lxrt.ko is soft link of rtai_sched.ko?
2) In rtai-3.8 version rtai_lxrt is not linked to any other module any specific reason?
3) I need rtai_lxrt individual module to be imported any idea how to do this?
4) I have python back end code which imports few of the module from rtai, since rtai_lxrt is not inserted  so i'm not able to import the same?
5) can I include rtai_lxrt header file to resolve python and rtai binding issue?
6) CONFIG_RTAI_LXRT_USE_LINUX_SYSCALL option is not available to configure in rtai-4.1 but same is available, any idea how to enable / explicitly overwrite this option?
7) How to get rtai_lxrt.ko as application scheduler, without soft link of rtai_sched?


Please share your views to resolve these issues , I'm stuck!!!
Appreciate your suggestions!!

Thanks

**Comment by ShabbyX** [comment]
@mrudulachougule Please open a new issue with unrelated questions. I opened and answered an issue for you [here](https://github.com/ShabbyX/RTAI/issues/26).
